create table if not exists `credit_card` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `openid` varchar(128) not null default '' comment 'openid',
    `unionid` varchar(128) not null default '' comment 'unionid',
    `bankId` smallint unsigned not null default '0' comment 'bankId',
    `name` varchar(64) not null default '' comment '姓名',
    `mobile` varchar(64) not null default '' comment '手机号',
    `idCard` varchar(24) not null default '' comment '身份证号',
    `channelSerial` int unsigned NOT NULL default '0' comment '流水号',
    `applyCompleted` char(3) not null default '' comment '进件标识;P：申请完成 D：申请未完成',  
    `applyCompletedData` varchar(24) not null default '' comment '进件时间',
    `applicationStatus` char(3) not null default '' comment '核卡标识;P： 审批通过 D：审批失败',
    `applicationStatusDate` varchar(24) not null default '' comment '核卡时间',
    `isNewUser` tinyint unsigned not null default '' comment '是否二卡 0否 1 二卡',
    `activated` char(3) not null default '' comment '激活标识;P：已激活 D：未激活',
    `activationDate` varchar(24) not null default '' comment '激活时间',
    `firstUsed` char(3) not null default '' comment '首刷标识;P：已首刷 D：未首刷',
    `firstUsedDate` varchar(24) not null default '' comment '首刷时间',
    `mark` varchar(256) not null default '' comment '备注',
    `create_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `openid` (`openid`),
    KEY `name` (`name`),
    KEY `mobile` (`mobile`),
    KEY `idCard` (`idCard`),
    KEY `channelSerial` (`channelSerial`),
    KEY `update_at` (`update_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;